Add text block edit functionality
premieroctet/digestclub pull request #12
Opened 2023-09-12 18:03 UTC by MrNossiom

Hi 👋🏻,

To add the ability of editing text blocks, I quickly duplicated the `EditBookmarkCard` file and modified the `.../{digestId}/block/{blockId}` endpoint `PATCH` implementation. Adding an `onEditClick` prop to the `BlockTextCard` component to show the `Edit` button in the Block Menu Popover. I did not change the dialog text yet.

Didn't test intensively, but it should work fine 😄 

## Improvements
- Merge `AddTextBlockDialog` and `EditTextBlockDialog` into one component?
- Cleanup the `.../{digestId}/block/{blockId}` file to avoid nesting. Factorize `if-else` statement in functions?

2023-09-13 11:47 UTC, shinework commented
Feature needed! 🙏  Thanks @MrNossiom

2023-09-14 12:03 UTC, shinework commented
Hello @MrNossiom! We have slightly updated the UI related to your PR, see https://github.com/premieroctet/digestclub/pull/15

2023-09-14 16:23 UTC, MrNossiom commented
I changed the button label of the `AddTextBlockDialog` from `Save` to `Add`. Just as a suggestion, I can revert it in seconds 😉.

2023-09-15 06:21 UTC, shinework requested changes

2023-09-15 06:21 UTC, shinework commented on src/components/digests/dialog/EditTextBlockDialog.tsx
> +export default function EditBookmarkDialog({
```suggestion
export default function EditTextBlockDialog({
```

2023-09-15 06:21 UTC, shinework commented on src/components/digests/dialog/EditTextBlockDialog.tsx
> +        successToast('Bookmark updated');
```suggestion
        successToast('Digest updated');
```

2023-09-15 17:02 UTC, shinework commented
Thanks @MrNossiom! I have spot a bug, when the user edits the text and re-edit, the textarea still contains the old text : 

https://github.com/premieroctet/digestclub/assets/1102595/e0088c79-b76c-4860-ac91-3c376073e09c

2023-09-15 17:38 UTC, MrNossiom commented
> I have spot a bug, when the user edits the text and re-edit, the textarea still contains the old text

Good catch 👍🏻

2023-09-16 11:16 UTC, shinework commented
Thanks a lot @MrNossiom! :shipit:

2023-09-16 11:16 UTC, shinework approved these changes

2023-09-16 11:17 UTC, merged